// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpZRQPTghvB5QphKAdQRpysZu3QK3hCI',
    appId: '1:1048215517288:web:fe13d0f3e5cf66abece3dd',
    messagingSenderId: '1048215517288',
    projectId: 'sports-ticketing',
    authDomain: 'sports-ticketing.firebaseapp.com',
    storageBucket: 'sports-ticketing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMc1UASyKZ_SupJ2UVeE-Su9RpaUE91x4',
    appId: '1:1048215517288:android:8c05cc2c57d1cba8ece3dd',
    messagingSenderId: '1048215517288',
    projectId: 'sports-ticketing',
    storageBucket: 'sports-ticketing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5iqPOZzwOiFQLSO1_19FcWkx_L42kpc',
    appId: '1:1048215517288:ios:f68485388d780ec2ece3dd',
    messagingSenderId: '1048215517288',
    projectId: 'sports-ticketing',
    storageBucket: 'sports-ticketing.appspot.com',
    iosBundleId: 'com.example.sportsTicketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi5iqPOZzwOiFQLSO1_19FcWkx_L42kpc',
    appId: '1:1048215517288:ios:f68485388d780ec2ece3dd',
    messagingSenderId: '1048215517288',
    projectId: 'sports-ticketing',
    storageBucket: 'sports-ticketing.appspot.com',
    iosBundleId: 'com.example.sportsTicketing',
  );
}
